### ISSUE TITLE
Was not able to load data training set

### ISSUE THREAD

**Issue by erinjerri** [random-forests/tensorflow-workshop#4]
``---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-0adb8d544c8a> in <module>()
----> 1 mnist = learn.datasets.load_dataset('mnist')
      2 data = mnist.train.images
      3 labels = np.asarray(mnist.train.labels, dtype=np.int32)
      4 test_data = mnist.test.images
      5 test_labels = np.asarray(mnist.test.labels, dtype=np.int32)

NameError: name 'learn' is not defined``

using Python 2.7 and anaconda.

**Comment by random-forests** [comment]
Thanks! I updated the notebooks. This shouldn't be an issue any longer.
