### ISSUE TITLE
Data not loading properly with matplotlib 

### ISSUE THREAD

**Issue by erinjerri** [random-forests/tensorflow-workshop#5]
I kept printing out this error when running Python 2.7 and anaconda, was not able to load data here, but on other parts of Juptyer Notebook it ran. 

`---------------------------------------------------------------------------
RuntimeError Traceback (most recent call last)
in ()
1 import numpy as np
----> 2 import matplotlib.pyplot as plt
3 get_ipython().magic(u'matplotlib inline')
4 import tensorflow as tf
5 learn = tf.contrib.learn

/Users/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/pyplot.py in ()
112 
113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
115 
116 _IP_REGISTERED = None

/Users/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/backends/init.pyc in pylab_setup()
30 # imports. 0 means only perform absolute imports.
31 backend_mod = import(backend_name,
---> 32 globals(),locals(),[backend_name],0)
33 
34 # Things we pull in from all backends

/Users/erinpangilinan/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py in ()
22 
23 import matplotlib
---> 24 from matplotlib.backends import _macosx
25 
26

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ`

**Comment by random-forests** [comment]
Thanks! I updated the installation instructions. This shouldn't be an issue any longer.
