### ISSUE TITLE
the 4th notebook doesn't loads MNIST after the call to it

### ISSUE THREAD

**Issue by z-a-f** [random-forests/tensorflow-workshop#6]
In the `4_mnist_low_level` notebook, if you uncomment the code in the 2nd code block, you will get a `NameError`. You are loading the `mnist` in the 3rd block, but the `2nd` one also needs it if it is uncommented.

**Comment by random-forests** [comment]
Thanks! I updated the notebooks. This shouldn't be an issue any longer.
